"""friendshipmodel

Revision ID: 0605b4b48c2e
Revises: 96cef118fc7c
Create Date: 2023-11-30 12:43:46.101095

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0605b4b48c2e'
down_revision = '96cef118fc7c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendship-relationship',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('friend_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['user.id'], name=op.f('fk_friendship-relationship_friend_id_user')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_friendship-relationship_user_id_user')),
    sa.PrimaryKeyConstraint('user_id', 'friend_id')
    )
    op.drop_table('friendships')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('friendships',
    sa.Column('user_id', sa.INTEGER(), nullable=False),
    sa.Column('friend_id', sa.INTEGER(), nullable=False),
    sa.ForeignKeyConstraint(['friend_id'], ['user.id'], name='fk_friendships_friend_id_user'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_friendships_user_id_user'),
    sa.PrimaryKeyConstraint('user_id', 'friend_id')
    )
    op.drop_table('friendship-relationship')
    # ### end Alembic commands ###
