"""edits Post table

Revision ID: c6201b101f7e
Revises: 6b28593812bb
Create Date: 2023-11-27 16:45:29.156752

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c6201b101f7e'
down_revision = '6b28593812bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.add_column(sa.Column('recipient_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_posts_recipient_id_user'), 'user', ['recipient_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('posts', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_posts_recipient_id_user'), type_='foreignkey')
        batch_op.drop_column('recipient_id')

    # ### end Alembic commands ###
